

security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # ...

    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: db_provider
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
                default_target_path: list_add
            logout:
                path: /logout
                target: list_add



    access_control:
        - { path: ^/ajout, roles: ROLE_USER }